# Generated by Django 2.2.3 on 2020-03-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawApp', '0002_userdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='name',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='LastName',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='company',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='degisnation',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='firstName',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='photo',
            field=models.ImageField(default=' ', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rawApp.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
